name: VFS Bulgaria Cloud Watcher

on:
  schedule:
    # 10 dakikada bir otomatik taranır (yoğunluktan etkilenmemek için 3,13,23,33,43,53 dakikalarında)
    - cron: '3,13,23,33,43,53 * * * *'
  workflow_dispatch:

jobs:
  check-vfs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Kodu Al
        uses: actions/checkout@v4

      - name: Saatlik Hafızayı Yükle
        uses: actions/cache@v4
        with:
          path: last_hour.txt
          key: vfs-hour-${{ github.run_id }}
          restore-keys: |
            vfs-hour-

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Paketleri Kur
        run: |
          pip install playwright requests
          playwright install chromium --with-deps

      - name: 12 Sehri Tara
        run: |
          python checker.py
